### ISSUE TITLE
the connection could not be established

### ISSUE THREAD

**Issue by PitaLife** [HEBK/wer-wird-millionaer#27] opened 2022-02-02 06:40 UTC
I've tried it, but the result can't enter the game, how do I do it

**Comment by Cr4zyFl1x** [comment] 2022-02-09 07:40
Hi @PitaLife,

can you please reproduce this issue and send me the console log?

You can open the software including the console as following:
`Start Menu > Wer Wird Milliönär > Wer Wird Millionär (Incl. Console)`

Kind regards,
Florian J. Kleine-Vorholt

**Comment by PitaLife** [comment] 2022-02-09 15:33
what is the password on that server on your game

**Comment by Cr4zyFl1x** [comment] 2022-02-09 17:30
Hi @PitaLife,

you need to setup a mysql database on your own.
The game will then connect to it and create the needed database structure.

If you want to do that locally on your computer you can easily [use MariaDB together with HeidiSQL](https://mariadb.org/download/) to manage the database.
However, you can also use a normal mysql database for example from a webspace if its reachable from all over the internet.

Kind regards,
Florian J. Kleine-Vorholt

**Comment by PitaLife** [comment] 2022-02-09 17:58
I've tried the MySQL you said, but it still doesn't work

**Comment by Cr4zyFl1x** [comment] 2022-02-09 19:12
Hi @PitaLife,

as I told you before: Can you please send me the console log?
Otherwise I can't help you with that issue.

I created a video guide for creating a database and user and how to connect:
https://cdn.kleine-vorholt.eu/tmp/share/StupendousZethusspinipes.mp4

Kind regards,
Florian J. Kleine-Vorholt

**Comment by Cr4zyFl1x** [comment] 2022-02-17 19:54
Because of missing response, I'll close this issue now.

**Closed as completed by Cr4zyFl1x** 2022-02-17 19:54 UTC
Labels: question
